import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import {
  buildSkillRouting,
  buildSkillRoutingWithRobustness,
  buildSkillRelationshipCache,
  computeParticleRobustness,
  needsRebuild,
  routeSkillsLexical,
  routeSkillsWithFusion,
  skillRoutingModeFromEnv,
  skillRoutingTopKFromEnv
} from '../dist/skill-router.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** 与 skill-router-cases.json 中 topShouldInclude 对齐的评测用 skill 池（模拟多领域重叠） */
function fixtureSkills() {
  return [
    {
      id: 'agent-tech-digest',
      name: 'Agent Tech Digest',
      description: 'Daily RSS digest for evolution pipeline',
      content:
        'Generated by evolution:learn. Covers MCP, agents, and tooling. See doc/evolution/inbox for run-day hooks.',
      source: 'workspace'
    },
    {
      id: 'pretty-mermaid',
      name: 'Pretty Mermaid',
      description: 'Render Mermaid diagrams as SVG',
      content:
        'Use the beautiful-mermaid library. Supports flowchart, sequence, state. Themes: default, dark, forest.',
      source: 'workspace'
    },
    {
      id: 'postgres-tuning',
      name: 'Postgres Tuning',
      description: 'Database performance tips',
      content:
        'Analyze slow queries with EXPLAIN ANALYZE. Add btree indexes for equality and range predicates. Consider VACUUM and autovacuum.',
      source: 'workspace'
    },
    {
      id: 'skill-authoring',
      name: 'Skill Authoring',
      description: 'How to write agent skills',
      content:
        'SKILL.md front matter with name and description. Progressive disclosure: keep body long but load on demand.',
      source: 'workspace'
    },
    {
      id: 'lark-mail',
      name: 'Lark Mail',
      description: 'Feishu email',
      content: 'Compose and send mail via Lark. Not related to diagrams.',
      source: 'agents'
    },
    {
      id: 'playwright-e2e',
      name: 'Playwright E2E',
      description: 'Browser automation for end-to-end testing',
      content: 'Use Playwright to click, fill forms, take screenshots, run assertions in CI pipelines.',
      source: 'workspace'
    },
    {
      id: 'git-workflow',
      name: 'Git Workflow',
      description: 'Git branching and merge',
      content: 'Prefer rebase for linear history. Resolve merge conflicts carefully before pushing.',
      source: 'workspace'
    },
    {
      id: 'docker-deploy',
      name: 'Docker Deploy',
      description: 'Container deployment',
      content: 'docker compose for local stacks. Multi-stage Dockerfile for smaller production images.',
      source: 'workspace'
    },
    {
      id: 'feishu-calendar',
      name: 'Feishu Calendar',
      description: '飞书日历与日程',
      content: '查询忙闲、创建会议、日程邀请。与飞书开放平台 API 对齐。',
      source: 'agents'
    },
    {
      id: 'python-conda',
      name: 'Python Conda',
      description: 'Python environments',
      content: 'conda create -n myenv python=3.11. Avoid polluting global pip when testing.',
      source: 'workspace'
    },
    {
      id: 'subagent-tips',
      name: 'Subagent Tips',
      description: 'Delegation patterns',
      content: 'Use spawn_subagent for bounded tasks. Parallel research and isolated implementation.',
      source: 'workspace'
    },
    {
      id: 'zzz-fallback',
      name: 'ZZZ Fallback',
      description: 'Alphabetically last placeholder',
      content: 'zzz alphabetical tie-break',
      source: 'workspace'
    }
  ];
}

test('routeSkillsLexical: JSON cases top-4 include expected name', async () => {
  const raw = await readFile(join(__dirname, 'skill-router-cases.json'), 'utf8');
  const { cases } = JSON.parse(raw);
  const skills = fixtureSkills();
  for (const c of cases) {
    const ranked = routeSkillsLexical(c.query, skills, 4);
    const names = ranked.map((r) => r.skill.name);
    assert.ok(
      names.includes(c.topShouldInclude),
      `query=${JSON.stringify(c.query)} expected ${c.topShouldInclude} in top-4, got ${names.join(', ')}`
    );
  }
});

test('buildSkillRouting: legacy exposes full shortlist count', () => {
  const skills = fixtureSkills();
  const r = buildSkillRouting('postgres index', skills, { mode: 'legacy', topK: 3 });
  assert.equal(r.mode, 'legacy');
  assert.equal(r.shortlistNames.length, skills.length);
  assert.ok(r.keywordMatched.length >= 0);
});

test('buildSkillRouting: hybrid unions keyword and lexical', () => {
  const skills = [
    {
      id: 'tasks',
      name: 'Tasks',
      description: 'task list',
      content: 'task_create long lived',
      source: 'builtin',
      triggerWords: ['task']
    },
    ...fixtureSkills().filter((s) => s.name !== 'ZZZ Fallback')
  ];
  const r = buildSkillRouting('task and postgres', skills, { mode: 'hybrid', topK: 3 });
  assert.ok(r.shortlistNames.includes('Tasks'));
  assert.ok(r.shortlistNames.includes('Postgres Tuning'));
});

test('skillRouting env helpers', () => {
  assert.equal(skillRoutingTopKFromEnv({ RAW_AGENT_SKILL_ROUTING_TOP_K: '3' }), 3);
  assert.equal(skillRoutingTopKFromEnv({ RAW_AGENT_SKILL_ROUTING_TOP_K: 'not-a-number' }), 8);
  assert.equal(skillRoutingModeFromEnv({ RAW_AGENT_SKILL_ROUTING_MODE: 'legacy' }), 'legacy');
  assert.equal(skillRoutingModeFromEnv({ RAW_AGENT_SKILL_ROUTING_MODE: 'lexical' }), 'lexical');
  assert.equal(skillRoutingModeFromEnv({}), 'hybrid');
});

test('buildSkillRouting: confidence is high for clear winner', () => {
  const skills = fixtureSkills();
  const r = buildSkillRouting('mermaid diagram flowchart', skills, { mode: 'hybrid', topK: 4 });
  assert.equal(r.confidence.level, 'high');
  assert.ok(r.confidence.scoreGap > 0);
  assert.ok(r.routed[0]?.skill.name.includes('Mermaid'));
});

test('buildSkillRouting: confidence is low for ambiguous query', () => {
  const skills = fixtureSkills();
  const r = buildSkillRouting('use', skills, { mode: 'hybrid', topK: 4 });
  assert.ok(['low', 'medium'].includes(r.confidence.level));
});

test('buildSkillRouting: confidence reflects no matches', () => {
  const skills = fixtureSkills();
  const r = buildSkillRouting('xyznonexistent', skills, { mode: 'hybrid', topK: 4 });
  assert.equal(r.confidence.level, 'low');
  assert.ok(r.confidence.reason.includes('no matching') || r.confidence.reason.includes('ambiguous'));
});

test('buildSkillRouting: legacy mode confidence reflects keyword match', () => {
  const skills = [
    {
      id: 'test-skill',
      name: 'Test Skill',
      description: 'A test',
      content: 'content',
      source: 'builtin',
      triggerWords: ['test']
    }
  ];
  const r = buildSkillRouting('test something', skills, { mode: 'legacy', topK: 4 });
  assert.equal(r.confidence.level, 'high');
  assert.ok(r.confidence.reason.includes('keyword match'));
});

test('buildSkillRouting: confidence provides score gap info', () => {
  const skills = fixtureSkills();
  const r = buildSkillRouting('postgres database performance', skills, { mode: 'hybrid', topK: 4 });
  assert.ok(typeof r.confidence.scoreGap === 'number');
  assert.ok(typeof r.confidence.nearTopCount === 'number');
  assert.ok(typeof r.confidence.reason === 'string');
});

test('computeParticleRobustness: returns high robustness for stable matches', () => {
  const skills = fixtureSkills();
  // Query with multiple specific tokens should have stable routing
  const { robustness, topSkillName } = computeParticleRobustness(
    'render mermaid flowchart diagram SVG',
    skills,
    3
  );
  assert.ok(robustness >= 0.6, `expected robustness >= 0.6, got ${robustness}`);
  assert.ok(topSkillName.includes('Mermaid'), `expected Mermaid skill, got ${topSkillName}`);
});

test('computeParticleRobustness: handles single token queries', () => {
  const skills = fixtureSkills();
  // Single token can't be perturbed much
  const { robustness } = computeParticleRobustness('test', skills, 3);
  assert.ok(typeof robustness === 'number');
});

test('buildSkillRoutingWithRobustness: adds robustness to confidence when enabled', () => {
  const skills = fixtureSkills();
  const r = buildSkillRoutingWithRobustness(
    'postgres database performance tuning',
    skills,
    { mode: 'hybrid', topK: 4, computeRobustness: true }
  );
  assert.ok(typeof r.confidence.robustness === 'number');
  assert.ok(r.confidence.robustness >= 0, 'robustness should be >= 0');
  assert.ok(r.confidence.robustness <= 1, 'robustness should be <= 1');
});

test('buildSkillRoutingWithRobustness: skips robustness when disabled', () => {
  const skills = fixtureSkills();
  const r = buildSkillRoutingWithRobustness(
    'postgres database performance',
    skills,
    { mode: 'hybrid', topK: 4, computeRobustness: false }
  );
  assert.equal(r.confidence.robustness, undefined);
});

test('buildSkillRoutingWithRobustness: legacy mode ignores robustness', () => {
  const skills = fixtureSkills();
  const r = buildSkillRoutingWithRobustness(
    'postgres database',
    skills,
    { mode: 'legacy', topK: 4, computeRobustness: true }
  );
  assert.equal(r.confidence.robustness, undefined);
});

test('routeSkillsWithFusion: boosts related skills', () => {
  const skills = fixtureSkills();
  const cache = buildSkillRelationshipCache(skills);
  const routed = routeSkillsWithFusion('mermaid diagram', skills, cache, 4);
  assert.ok(routed.length > 0);
  assert.ok(routed[0].score >= 0);
});

test('routeSkillsLexical: aliases contribute to routing score', () => {
  const skills = fixtureSkills().map((skill) =>
    skill.name === 'Pretty Mermaid'
      ? { ...skill, aliases: ['diagram renderer'] }
      : skill
  );
  const routed = routeSkillsLexical('diagram renderer svg', skills, 3);
  assert.equal(routed[0]?.skill.name, 'Pretty Mermaid');
  assert.ok(routed[0]?.reason.includes('alias:diagram') || routed[0]?.reason.includes('alias:renderer'));
});

test('needsRebuild: cache invalidates when routing-relevant metadata changes', () => {
  const skills = fixtureSkills();
  const cache = buildSkillRelationshipCache(skills);
  const updated = skills.map((skill) =>
    skill.name === 'Pretty Mermaid'
      ? { ...skill, aliases: ['diagram renderer'] }
      : skill
  );
  assert.equal(needsRebuild(cache, updated), true);
});
