apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ppeng
resources:
  - namespace.yaml
  - pvc.yaml
  - daemon.yaml
  - web.yaml
images:
  - name: ghcr.io/magele758/ppeng-agent-core/daemon
    newTag: nightly
  - name: ghcr.io/magele758/ppeng-agent-core/web
    newTag: nightly
