/**
 * Worktree-side helpers for evolution-run-day:
 *   - White-listed `.env` writer (avoids shipping API keys into N parallel worktrees)
 *   - Gateway config copier (with shared-with-core resolver)
 *   - Worktree teardown
 */
import { existsSync } from 'node:fs';
import { copyFile, rm, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { run, truthy } from './process.mjs';

const EVOLUTION_ENV_DEFAULT_PASSTHRU_PREFIXES = [
  'EVOLUTION_',
  'RAW_AGENT_GATEWAY_',
  'RAW_AGENT_FEED_'
];
const EVOLUTION_ENV_DEFAULT_PASSTHRU_EXACT = new Set([
  'RAW_AGENT_STATE_DIR',
  'AI_CODEX_FULL_AUTO'
]);

/** Build the contents of a worktree-local `.env` file from process.env using whitelist. */
export function buildEvolutionEnvFile() {
  const extraKeys = (process.env.EVOLUTION_ENV_PASSTHRU_KEYS || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const allowExact = new Set([...EVOLUTION_ENV_DEFAULT_PASSTHRU_EXACT, ...extraKeys]);
  const lines = [
    '# evolution worktree env (auto-generated by evolution-run-day.mjs)',
    '# Only non-sensitive evolution-related keys; model API keys stay in the main .env.',
    ''
  ];
  for (const k of Object.keys(process.env).sort()) {
    if (
      !allowExact.has(k) &&
      !EVOLUTION_ENV_DEFAULT_PASSTHRU_PREFIXES.some((p) => k.startsWith(p))
    ) continue;
    const v = process.env[k];
    if (v === undefined) continue;
    if (/[\n"\\]/.test(v)) {
      const escaped = v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
      lines.push(`${k}="${escaped}"`);
    } else {
      lines.push(`${k}=${v}`);
    }
  }
  return lines.join('\n') + '\n';
}

/**
 * Write the worktree `.env`. Honour EVOLUTION_SKIP_COPY_ENV / EVOLUTION_ENV_FILE.
 * Default behaviour is the safe whitelist export (NOT a literal copy of repoRoot/.env).
 */
export async function copyEnvToWorktree(repoRoot, wtPath, itemTrace) {
  if (truthy(process.env.EVOLUTION_SKIP_COPY_ENV)) {
    itemTrace('未拷贝 .env（EVOLUTION_SKIP_COPY_ENV=1）');
    return;
  }
  const explicit = process.env.EVOLUTION_ENV_FILE?.trim();
  if (explicit) {
    const src = explicit.startsWith('/') ? explicit : join(repoRoot, explicit);
    if (!existsSync(src)) {
      itemTrace(`EVOLUTION_ENV_FILE 指定的路径不存在: ${src}`);
      return;
    }
    try {
      await copyFile(src, join(wtPath, '.env'));
      itemTrace(`已拷贝显式 env 文件 ${src} → worktree/.env`);
    } catch (e) {
      itemTrace(`拷贝 ${src} 失败: ${e instanceof Error ? e.message : String(e)}`);
    }
    return;
  }
  try {
    await writeFile(join(wtPath, '.env'), buildEvolutionEnvFile(), 'utf8');
    itemTrace('已写出白名单 .env → worktree（仅 EVOLUTION_* / RAW_AGENT_GATEWAY_* / RAW_AGENT_FEED_*）');
  } catch (e) {
    itemTrace(`写出 worktree .env 失败（继续执行）: ${e instanceof Error ? e.message : String(e)}`);
  }
}

/** Use the unified resolver from core (single source of truth across the repo). */
export async function resolveGatewayConfigSourcePath(repoRoot) {
  const { findGatewayConfigPath } = await import(
    pathToFileURL(join(repoRoot, 'packages/core/dist/gateway-config-channels.js')).href
  );
  return findGatewayConfigPath(repoRoot);
}

export async function copyGatewayConfigToWorktree(repoRoot, wtPath, itemTrace) {
  if (truthy(process.env.EVOLUTION_SKIP_COPY_GATEWAY_CONFIG)) {
    itemTrace('未拷贝 gateway 配置（EVOLUTION_SKIP_COPY_GATEWAY_CONFIG=1）');
    return;
  }
  const src = await resolveGatewayConfigSourcePath(repoRoot);
  if (!src) {
    itemTrace('主仓无 gateway.config.json / gateway.config.example.json，跳过拷贝');
    return;
  }
  const destName = basename(src) === 'gateway.config.example.json' ? 'gateway.config.json' : basename(src);
  const dest = join(wtPath, destName);
  try {
    await copyFile(src, dest);
    itemTrace(`已拷贝 ${basename(src)} → worktree/${destName}`);
  } catch (e) {
    itemTrace(`拷贝 gateway 配置失败（继续执行）: ${e instanceof Error ? e.message : String(e)}`);
  }
}

/**
 * Tear down a worktree:
 *   1. `git worktree remove --force` to release the branch.
 *   2. `rm -rf` for any leftover directory tree.
 *   3. Optionally `git branch -D <branch>` once callers know the branch is no longer needed.
 */
export async function removeWorktree(repoRoot, wtPath, branch = '', itemTrace = () => {}, deleteBranch = true) {
  const hadPath = existsSync(wtPath);
  const r1 = await run(repoRoot, 'git', ['worktree', 'remove', '--force', wtPath], { cwd: repoRoot });
  if (r1.code !== 0) {
    const msg = (r1.err || r1.out).slice(0, 200);
    if (hadPath || !/is not a working tree/i.test(msg)) {
      itemTrace(`worktree 移除失败 exit=${r1.code}: ${msg}`);
    }
  }
  try {
    await rm(wtPath, { recursive: true, force: true });
  } catch (e) {
    itemTrace(`rm 残留目录失败: ${e instanceof Error ? e.message : String(e)}`);
  }
  if (deleteBranch && branch) {
    const r3 = await run(repoRoot, 'git', ['branch', '-D', branch], { cwd: repoRoot });
    if (r3.code !== 0) {
      const msg = (r3.err || r3.out).slice(0, 200);
      if (!/not found/i.test(msg)) {
        itemTrace(`分支删除失败 ${branch} exit=${r3.code}: ${msg}`);
      }
    }
  }
}
