apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ppeng-agent-core.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  RAW_AGENT_STATE_DIR: /data/state
  RAW_AGENT_DAEMON_HOST: "0.0.0.0"
  RAW_AGENT_DAEMON_PORT: "7070"
  NODE_ENV: production
