apiVersion: v1
kind: Service
metadata:
  name: {{ include "ppeng-agent-core.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
